services:
  api:
    build: ./api
    container_name: express_api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: netuser
      POSTGRES_PASSWORD: netpass
      POSTGRES_DB: netdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro

  db_test:
    image: postgres:16
    container_name: postgres_db_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: netdb_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro

  frontend:
    build: ./frontend
    container_name: react_frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

volumes:
  pgdata:
  pgdata_test:
